name = "Primes"
uuid = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[extras]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataStructures", "Test"]
